const mockJobOnRun = [
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [
            {
                "Guid": "ef8a4322-039a-4290-9b17-4dd3b26a2c29",
                "JobNo": "0010653601500",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 12:33:00",
                "SequenceStop": 1,
                "LocationName": "Listerine - T1000",
                "WindowsTimeServiceTimeStart": "12:33",
                "ActualTime": "15:32",
                "RouteGroupDetailName": "CP-001",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": true,
                "MasterCustomerLocation_Guid": "2dc1103f-64d5-444c-a800-5efe9087d281",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "d3dbd06f-71c5-6357-070f-6feb3c1f1bfa",
                "SystemStatusJobID": 9,
                "MasterRunResource_Guid": "32c7f0a5-5450-08b4-b87e-3f5f7d5385f7",
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Closed",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_closed.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "FlagSyncToMobile": 7,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": null,
                "UserModifed": "YotinG",
                "Remarks": "Ticket#392942422 | Comments: -",
                "ServiceStopLegsGuid": "516b14b0-c57d-4d53-8458-0bb87ab0e3d7",
                "DepartTime": "15:32",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 0,
                "City": "",
                "District": "เขตคลองเตย",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "skynet 2014",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 2,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 1,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": "123456",
                "UnassignedBy": null,
                "UnassignedDatetime": "2024/02/20 12:34:15",
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": "392942422",
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            }
        ],
        "JobsUnassigned": [],
        "TotalJobs": 1,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    },
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [
            {
                "Guid": "fdb0175e-510b-433d-8a9e-a4fe51830992",
                "JobNo": "0010653613532",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 15:42:00",
                "SequenceStop": 1,
                "LocationName": "Love Yourself - All Cap",
                "WindowsTimeServiceTimeStart": "15:42",
                "ActualTime": "15:45",
                "RouteGroupDetailName": "CNPY-001",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": true,
                "MasterCustomerLocation_Guid": "ec65796c-7b24-47a6-a27a-df116f9b02e8",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "00152332-3819-a734-c071-ba2030991879",
                "SystemStatusJobID": 9,
                "MasterRunResource_Guid": "4d948591-0807-a018-9fed-b0ef1c003159",
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Closed",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_closed.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "FlagSyncToMobile": 7,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": null,
                "UserModifed": "YotinG",
                "Remarks": "Ticket#392943114 | Comments: -",
                "ServiceStopLegsGuid": "b7599a89-317c-4d30-bca4-a62d7449eb96",
                "DepartTime": "15:45",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 0,
                "City": "",
                "District": "เขตบางคอแหลม",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "123 manod",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 2,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 1,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": "1412141213",
                "UnassignedBy": null,
                "UnassignedDatetime": null,
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": "392943114",
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            }
        ],
        "JobsUnassigned": [],
        "TotalJobs": 1,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    },
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [
            {
                "Guid": "b85b5c07-3f13-4263-8029-0f375849f6bc",
                "JobNo": "0010653618078",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 16:07:00",
                "SequenceStop": 1,
                "LocationName": "Love Yourself - Love Brinks-Boxz",
                "WindowsTimeServiceTimeStart": "16:07",
                "ActualTime": "17:02",
                "RouteGroupDetailName": "R1",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": true,
                "MasterCustomerLocation_Guid": "39c2fa09-5f20-4bd9-836f-dc00b1e76400",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "53c689b4-c1b4-7755-f4eb-81d6728b4b8e",
                "SystemStatusJobID": 9,
                "MasterRunResource_Guid": "57b65efa-1b55-5a7c-1633-ff636e98c5f3",
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Closed",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_closed.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "FlagSyncToMobile": 7,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": null,
                "UserModifed": "YotinG",
                "Remarks": "Ticket#392948862 | Comments: -",
                "ServiceStopLegsGuid": "8aa7a257-0a32-4598-a5de-1eec6597d29a",
                "DepartTime": "17:02",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 0,
                "City": "",
                "District": "เขตตลิ่งชัน",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "513513",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 2,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 1,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": "1900190002",
                "UnassignedBy": null,
                "UnassignedDatetime": null,
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": "392948862",
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            }
        ],
        "JobsUnassigned": [],
        "TotalJobs": 1,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    },
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [
            {
                "Guid": "dd3715c1-d41f-440c-8a1b-ce8f1ee7cb46",
                "JobNo": "0010653672536",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "CIT",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "_@Yotest - Yo_@",
                "WindowsTimeServiceTimeStart": "00:00",
                "ActualTime": null,
                "RouteGroupDetailName": "TUM-RD 200x10 SRC",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "d0128364-f818-42df-ac88-4a6ab0adb155",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "e8486d3c-ccec-478c-ab65-baa7e097d47a",
                "SystemStatusJobID": 2,
                "MasterRunResource_Guid": "66f709ab-4ced-f5fe-d3eb-5ae2874a4aae",
                "ServiceJobTypeNameAbb": "P",
                "ServiceJobTypeID": 0,
                "OnwardDestinationLocation": "",
                "JobStatus": "On Truck",
                "ActionFlag": "P",
                "ServiceHour": " 00:00-23:59",
                "PathImageStatus": "../Images/RunControl/job_ontruck.png",
                "SystemLineOfBusiness_Guid": "db65f1db-8c61-436d-b762-cc585df27547",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "FlagSyncToMobile": 0,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "YotinG",
                "UserModifed": "YotinG",
                "Remarks": "",
                "ServiceStopLegsGuid": "606341e8-8101-4f33-b522-58f4781cf024",
                "DepartTime": null,
                "ServiceJobTypeName": "Pick Up",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 1,
                "City": "CITBOTDIAN",
                "District": "DISBOTDIAN",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "123456789",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 3,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 0,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": "11122231",
                "UnassignedBy": "YotinG",
                "UnassignedDatetime": "2024/02/22 14:27:03",
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": null,
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            },
            {
                "Guid": "6770e046-784a-4d16-b4c7-abcb0556404b",
                "JobNo": "0010653673996",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "CIT",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - !LOC A 10",
                "WindowsTimeServiceTimeStart": "00:00",
                "ActualTime": null,
                "RouteGroupDetailName": "TUM-RD 200x10 SRC",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "fa70107b-e53c-4c3f-88c8-51e6c19a74ff",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "e8486d3c-ccec-478c-ab65-baa7e097d47a",
                "SystemStatusJobID": 2,
                "MasterRunResource_Guid": "66f709ab-4ced-f5fe-d3eb-5ae2874a4aae",
                "ServiceJobTypeNameAbb": "P",
                "ServiceJobTypeID": 0,
                "OnwardDestinationLocation": "",
                "JobStatus": "On Truck",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_ontruck.png",
                "SystemLineOfBusiness_Guid": "db65f1db-8c61-436d-b762-cc585df27547",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 2,
                "FlagSyncToMobile": 0,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "YotinG",
                "UserModifed": "YotinG",
                "Remarks": "",
                "ServiceStopLegsGuid": "ccd2ec93-18a1-433b-a611-1b5cdb6bbba2",
                "DepartTime": null,
                "ServiceJobTypeName": "Pick Up",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 1,
                "City": "",
                "District": "เขตคลองเตย",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "test111111",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 3,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 0,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": "TEST111111",
                "UnassignedBy": "YotinG",
                "UnassignedDatetime": "2024/02/22 14:27:13",
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": null,
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            },
            {
                "Guid": "c6bd63cf-17cf-4692-8b7a-2cc9e57254e5",
                "JobNo": "0010653674133",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "CIT",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "__MultiBranch - BCD_Test",
                "WindowsTimeServiceTimeStart": "00:00",
                "ActualTime": null,
                "RouteGroupDetailName": "TUM-RD 200x10 SRC",
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "85999235-c2c7-49b0-a0fa-85b4aeb5ecea",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": "e8486d3c-ccec-478c-ab65-baa7e097d47a",
                "SystemStatusJobID": 2,
                "MasterRunResource_Guid": "66f709ab-4ced-f5fe-d3eb-5ae2874a4aae",
                "ServiceJobTypeNameAbb": "P",
                "ServiceJobTypeID": 0,
                "OnwardDestinationLocation": "",
                "JobStatus": "On Truck",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_ontruck.png",
                "SystemLineOfBusiness_Guid": "db65f1db-8c61-436d-b762-cc585df27547",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 3,
                "FlagSyncToMobile": 0,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "YotinG",
                "UserModifed": "YotinG",
                "Remarks": "",
                "ServiceStopLegsGuid": "45c81c77-5e58-452e-b2c5-600750eef133",
                "DepartTime": null,
                "ServiceJobTypeName": "Pick Up",
                "CustomerLocationDelivery": "",
                "FlagNextStop": false,
                "FlagUsingAdhocJob": 1,
                "City": "",
                "District": "",
                "City_Delivery": "",
                "District_Delivery": "",
                "CustomerLocationAddressDelivery": "",
                "LocationAddress": "",
                "FlagRouteBalanceDone": false,
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "SeqIndex": 1,
                "STC": "0.00",
                "FlagAllowEditJob": 0,
                "LOBInternalID": 3,
                "TotalItems": 0,
                "Commodity": null,
                "FlagIsEmptyJob": true,
                "FlagIsSFO": 0,
                "ReasonUnableGuid": null,
                "FlagPartialRouteBalanceDone": false,
                "MachineID": null,
                "UnassignedBy": "YotinG",
                "UnassignedDatetime": "2024/02/22 14:27:21",
                "ReasonUnableToServiceDateTime": "",
                "TicketNumber": null,
                "FlagMultipleCurrency": false,
                "FlagMoneyProcessing": false,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": null,
                "FlagNonDelivery": false
            }
        ],
        "JobsUnassigned": [],
        "TotalJobs": 3,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    }
]

const mockUnAssign = [
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [],
        "JobsUnassigned": [
            {
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            }
        ],
        "TotalJobs": 1,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    }
]

const mockUnAssign2 = [
    {
        "JobsVehicleStop": [],
        "JobsServiceStop": [],
        "Jobs": [],
        "JobsUnassigned": [
            {
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },
            {
                "Guid": "7cfeca13-14e9-48aa-8eae-36a173746ae0",
                "JobNo": "0010653675249",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "CIT",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "Aloha - Big Cleaning Day",
                "WindowsTimeServiceTimeStart": "00:00",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "604f7b07-ae4b-4580-84eb-5b9616dee07e",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "P",
                "ServiceJobTypeID": 0,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "db65f1db-8c61-436d-b762-cc585df27547",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "YotinG",
                "UserModifed": "",
                "Remarks": "",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "1dec2180-f819-4f95-a209-4f92d3912bb7",
                "ServiceJobTypeName": "Pick Up",
                "CustomerLocationDelivery": "Aloha - Big Cleaning Day",
                "City": null,
                "District": "เขตคลองสาน",
                "City_Delivery": "",
                "District_Delivery": "เขตคลองสาน",
                "LocationAddress": "",
                "CustomerLocationAddressDelivery": "",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "37e2f276-c461-4ab8-a22f-62d3673cd16a",
                "STC": "0.00",
                "LOBInternalID": 3,
                "FlagIsSFO": 0,
                "Commodity": null,
                "MachineID": null,
                "UnassignedDatetime": "22-02-2024 14:27",
                "UnassignedBy": "YotinG",
                "FlagIntDisc": false,
                "TicketNumber": null,
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },
            {
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },
            {
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },{
                "Guid": "1560b5c7-8ef5-4beb-afb7-590bd2518161",
                "JobNo": "0010653600701",
                "FlagCancelAll": false,
                "ServiceStopTypeName": "Service Stop",
                "LOBAbbrevaitionName": "ATM",
                "TransectionDate": "2024/02/20 00:00:00",
                "SequenceStop": 1,
                "LocationName": "!Client 01 - LOC A 20",
                "WindowsTimeServiceTimeStart": "12:32",
                "RouteGroupDetailName": null,
                "CustomerLocationAction_Guid": "db81aee9-9a66-4d69-9d6f-5a407c1b7069",
                "FlagJobClose": false,
                "MasterCustomerLocation_Guid": "9d4374cc-a3fc-4ebf-9a59-b8bca50cbc34",
                "FlagHalfFinish": false,
                "FlagJobDiscrepancies": false,
                "FlagCustomer": true,
                "FlagJob247": null,
                "MasterSite_Guid": "742346f7-f2e8-4347-ad07-77a2811ee636",
                "MasterRouteGroupDetail_Guid": null,
                "SystemStatusJobID": 1,
                "MasterRunResource_Guid": null,
                "ServiceJobTypeNameAbb": "FLM",
                "ServiceJobTypeID": 6,
                "OnwardDestinationLocation": "",
                "JobStatus": "Open",
                "ActionFlag": "P",
                "ServiceHour": null,
                "PathImageStatus": "../Images/RunControl/job_open.png",
                "SystemLineOfBusiness_Guid": "a6d0d672-1b43-407e-b738-31d65baf9115",
                "SystemStopType_Guid": "095b7148-2829-42ff-9017-b7ab6472065d",
                "JobOrder": 1,
                "SeqIndex": 1,
                "Country": "",
                "AirprotCode": "",
                "AirprotName": "",
                "AirportDocChecked": "False",
                "AirprotGuid": null,
                "FlightNo": "",
                "ETD": "00:00",
                "ETA": "00:00",
                "Weights": 0,
                "Pieces": 0,
                "MAWB": "",
                "HAWB": 0,
                "FlagEarlyFlight": "False",
                "RevisedTime": "00:00",
                "UserCreated": "",
                "UserModifed": "",
                "Remarks": "Ticket#392941277 | Comments: -",
                "DayInVault": 0,
                "ServiceStopLegsGuid": "b0bfd895-edd0-4978-a511-39377c13741c",
                "ServiceJobTypeName": "First Line Maintenance",
                "CustomerLocationDelivery": "!Client 01 - LOC A 20",
                "City": null,
                "District": "อำเภอเด่นชัย",
                "City_Delivery": "",
                "District_Delivery": "อำเภอเด่นชัย",
                "LocationAddress": "55555",
                "CustomerLocationAddressDelivery": "55555",
                "FlagJobInterBranch": false,
                "FlagChkOutInterBranchComplete": false,
                "DayOfWeekGuid": "106d2ca8-4c38-4ad3-bea3-f8da9452fa29",
                "JobTypeGuid": "df8a1b04-e90b-4613-af3b-7d2764709861",
                "STC": "0.00",
                "LOBInternalID": 2,
                "FlagIsSFO": 1,
                "Commodity": null,
                "MachineID": "1234",
                "UnassignedDatetime": "20-02-2024 12:32",
                "UnassignedBy": null,
                "FlagIntDisc": false,
                "TicketNumber": "392941277",
                "SystemStatusShuttleJobID": null,
                "ActionNameAbbrevaition": "P"
            },
        ],
        "TotalJobs": 2,
        "TotalSTC": 0,
        "FlagCentralOverride": false,
        "Message": {
            "IsSuccess": true,
            "IsWarning": false,
            "MsgID": 0,
            "SystemLanguage_Guid": "6fa2bd67-0794-4a9e-a13b-2d81ddb574a0",
            "MessageTextContent": "Success",
            "MessageTextTitle": "Success (Msg ID: 0)",
            "MessageTextTitleEncoded": null
        }
    }
]

export const mockRunControl = {
    getRun() {
        return [
            {
                "Guid": "32c7f0a5-5450-08b4-b87e-3f5f7d5385f7",
                "MasterRunResourceShift": 1,
                "VehicleNumber": "00001",
                "MasterRouteGroup_Detail_Guid": "d3dbd06f-71c5-6357-070f-6feb3c1f1bfa",
                "MasterRouteGroupDetailName": "CP-001",
                "MasterRouteGroupName": "Canopy",
                "ModeOfTransport": "Vehicle",
                "RunResourceDailyStatusID": 3,
                "RunResourceDailyStatusName": "Closed Run",
                "TotalJobInRun": 1,
                "TotalJobNotSync": 1,
                "MasterRunResource_Guid": "a036a512-896a-4bdc-bd94-aaabd088c973",
                "VehicleNumberFullName": "00001",
                "WorkDate": "/Date(1708362000000)/",
                "strWorDate": "20-02-2024",
                "MasterGroupGuid": "89a3f8f9-6716-48a5-a00a-a1275150f4be",
                "ModeOfTransportGuid": "5076ef79-0c77-42c6-8737-7eb39cf1bacc",
                "DailyStatusID": 3,
                "DailyStatusName": "Closed Run",
                "PathPicModeOfTransport": "/Images/RunControl/vehicle_C_not_sync.png",
                "FlagUseMobile": 1,
                "FlagOverNight": false,
                "DetailRun": "/images/CrewManagement/Crew.png|CC|990009|Super  Nova|CC",
                "FlagRouteBalanceDone": false,
                "FlagAlarmLock": false,
                "ModeOfTransportID": 1,
                "LiabilityLimitCurrency_Guid": "82011826-b47d-4747-a533-a89f42decf24",
                "LiabilityLimitCurrencyAbb": "USD",
                "FlagShuttleRun": false,
                "FlagPercentageLiabilityLimitAlert": false
            },
            {
                "Guid": "4d948591-0807-a018-9fed-b0ef1c003159",
                "MasterRunResourceShift": 2,
                "VehicleNumber": "00001",
                "MasterRouteGroup_Detail_Guid": "00152332-3819-a734-c071-ba2030991879",
                "MasterRouteGroupDetailName": "CNPY-001",
                "MasterRouteGroupName": "CNPY",
                "ModeOfTransport": "Vehicle",
                "RunResourceDailyStatusID": 2,
                "RunResourceDailyStatusName": "Dispatch Run",
                "TotalJobInRun": 1,
                "TotalJobNotSync": 1,
                "MasterRunResource_Guid": "a036a512-896a-4bdc-bd94-aaabd088c973",
                "VehicleNumberFullName": "00001 (S2)",
                "WorkDate": "/Date(1708362000000)/",
                "strWorDate": "20-02-2024",
                "MasterGroupGuid": "31fff18f-fb7a-4a81-8432-c8e9b79144d3",
                "ModeOfTransportGuid": "5076ef79-0c77-42c6-8737-7eb39cf1bacc",
                "DailyStatusID": 2,
                "DailyStatusName": "Dispatch Run",
                "PathPicModeOfTransport": "/Images/RunControl/vehicle_D_not_sync.png",
                "FlagUseMobile": 1,
                "FlagOverNight": false,
                "DetailRun": "/images/CrewManagement/Crew.png|CC|IMPORT01|IMPORT01  IMPORT01|CC",
                "FlagRouteBalanceDone": false,
                "FlagAlarmLock": false,
                "ModeOfTransportID": 1,
                "LiabilityLimitCurrency_Guid": "82011826-b47d-4747-a533-a89f42decf24",
                "LiabilityLimitCurrencyAbb": "USD",
                "FlagShuttleRun": false,
                "FlagPercentageLiabilityLimitAlert": false
            },
            {
                "Guid": "57b65efa-1b55-5a7c-1633-ff636e98c5f3",
                "MasterRunResourceShift": 3,
                "VehicleNumber": "00001",
                "MasterRouteGroup_Detail_Guid": "53c689b4-c1b4-7755-f4eb-81d6728b4b8e",
                "MasterRouteGroupDetailName": "R1",
                "MasterRouteGroupName": "Tum Group",
                "ModeOfTransport": "Vehicle",
                "RunResourceDailyStatusID": 2,
                "RunResourceDailyStatusName": "Dispatch Run",
                "TotalJobInRun": 1,
                "TotalJobNotSync": 1,
                "MasterRunResource_Guid": "a036a512-896a-4bdc-bd94-aaabd088c973",
                "VehicleNumberFullName": "00001 (S3)",
                "WorkDate": "/Date(1708362000000)/",
                "strWorDate": "20-02-2024",
                "MasterGroupGuid": "63416f54-5bc9-4154-a924-e5031027dd3e",
                "ModeOfTransportGuid": "5076ef79-0c77-42c6-8737-7eb39cf1bacc",
                "DailyStatusID": 2,
                "DailyStatusName": "Dispatch Run",
                "PathPicModeOfTransport": "/Images/RunControl/vehicle_D_not_sync.png",
                "FlagUseMobile": 1,
                "FlagOverNight": false,
                "DetailRun": "/images/CrewManagement/Crew.png|CC|T0002|Emp12 test last1|CC",
                "FlagRouteBalanceDone": false,
                "FlagAlarmLock": false,
                "ModeOfTransportID": 1,
                "LiabilityLimitCurrency_Guid": "82011826-b47d-4747-a533-a89f42decf24",
                "LiabilityLimitCurrencyAbb": "USD",
                "FlagShuttleRun": false,
                "FlagPercentageLiabilityLimitAlert": false
            }
        ]
    },
    getJobOnRun(runGuid) {
        return mockJobOnRun.filter(item => item.Jobs[0].MasterRunResource_Guid === runGuid)
        // return mockJobOnRun[3]
    },
    getUnAssignJob() {
        // return mockUnAssign;
        return mockUnAssign2;
    }
}
