import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic'
const SidebarDemo = dynamic(() => import('../app/components/Sidebar'))


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          id="theme-link"
          href={`/themes/lara-light-blue/theme.css`}
          rel="stylesheet"
        ></link>
      </head>
      <body id="bodyMain" className={`${inter.className} h-screen w-full`}>
      {/* <SidebarDemo /> */}
        {children}
      </body>
    </html>
  );
}
